version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: rustup version
          command: rustup --version
      - run:
          name: rustup component add
          command: rustup component add clippy rustfmt
      - run:
          name: fmt
          command: cargo fmt -- --check
      - run:
          name: setup sccache
          command: |
            cargo install sccache cargo-tarpaulin
            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
            echo 'export "SCCACHE_CACHE_SIZE"="1G"' >> $BASH_ENV

      - restore_cache:
          name: Restore sccache cache
          key: sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: build
          command: cargo build
      - run:
          name: lint
          command: cargo clippy -- -D warnings
      - run:
          name: test
          command: |
            # cargo test
            bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
            cargo tarpaulin --all-features --out Xml
            bash <(curl -s https://codecov.io/bash)
      - save_cache:
          name: Save sccache cache
          key: sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - "~/.cache/sccache"
